// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.118Z
// Icon: book

import type { SVGProps } from "react";

export interface BookProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Book({ size = 24, ...props }: BookProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>book</title>
      <path
        fill="currentColor"
        d="M8 2h12v20H4V2zm4 8h-2v2H8V4H6v16h12V4h-4v8h-2z"
      />
    </svg>
  );
}

Book.displayName = "Book";
