// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.121Z
// Icon: clock

import type { SVGProps } from "react";

export interface ClockProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Clock({ size = 24, ...props }: ClockProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>clock</title>
      <path
        fill="currentColor"
        d="M19 3H5v2H3v14h2v2h14v-2h2V5h-2zm0 2v14H5V5zm-8 2h2v6h4v2h-6z"
      />
    </svg>
  );
}

Clock.displayName = "Clock";
