// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.127Z
// Icon: coin

import type { SVGProps } from "react";

export interface CoinProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Coin({ size = 24, ...props }: CoinProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>coin</title>
      <path
        fill="currentColor"
        d="M6 2h12v2H6zM4 6V4h2v2zm0 12V6H2v12zm2 2v-2H4v2zm12 0v2H6v-2zm2-2v2h-2v-2zm0-12h2v12h-2zm0 0V4h-2v2zm-9-1h2v2h3v2h-6v2h6v6h-3v2h-2v-2H8v-2h6v-2H8V7h3z"
      />
    </svg>
  );
}

Coin.displayName = "Coin";
