// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.128Z
// Icon: copy

import type { SVGProps } from "react";

export interface CopyProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Copy({ size = 24, ...props }: CopyProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>copy</title>
      <path
        fill="currentColor"
        d="M4 2h11v2H6v13H4zm4 4h12v16H8zm2 2v12h8V8z"
      />
    </svg>
  );
}

Copy.displayName = "Copy";
