// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.129Z
// Icon: device-phone

import type { SVGProps } from "react";

export interface DevicePhoneProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function DevicePhone({ size = 24, ...props }: DevicePhoneProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>device-phone</title>
      <path
        fill="currentColor"
        d="M6 3h12v18H6zm10 16V5h-2v2h-4V5H8v14zm-5-4h2v2h-2z"
      />
    </svg>
  );
}

DevicePhone.displayName = "DevicePhone";
