// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.131Z
// Icon: download

import type { SVGProps } from "react";

export interface DownloadProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Download({ size = 24, ...props }: DownloadProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>download</title>
      <path
        fill="currentColor"
        d="M13 17V3h-2v10H9v-2H7v2h2v2h2v2zm8 2v-4h-2v4H5v-4H3v6h18zm-8-6v2h2v-2h2v-2h-2v2z"
      />
    </svg>
  );
}

Download.displayName = "Download";
