// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.133Z
// Icon: edit

import type { SVGProps } from "react";

export interface EditProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Edit({ size = 24, ...props }: EditProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>edit</title>
      <path
        fill="currentColor"
        d="M18 2h-2v2h-2v2h-2v2h-2v2H8v2H6v2H4v2H2v6h6v-2h2v-2h2v-2h2v-2h2v-2h2v-2h2V8h2V6h-2V4h-2zm0 8h-2v2h-2v2h-2v2h-2v2H8v-2H6v-2h2v-2h2v-2h2V8h2V6h2v2h2zM6 16H4v4h4v-2H6z"
      />
    </svg>
  );
}

Edit.displayName = "Edit";
