// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.134Z
// Icon: external-link

import type { SVGProps } from "react";

export interface ExternalLinkProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function ExternalLink({ size = 24, ...props }: ExternalLinkProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>external-link</title>
      <path
        fill="currentColor"
        d="M21 11V3h-8v2h4v2h-2v2h-2v2h-2v2H9v2h2v-2h2v-2h2V9h2V7h2v4zM11 5H3v16h16v-8h-2v6H5V7h6z"
      />
    </svg>
  );
}

ExternalLink.displayName = "ExternalLink";
