// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.135Z
// Icon: gamepad

import type { SVGProps } from "react";

export interface GamepadProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Gamepad({ size = 24, ...props }: GamepadProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>gamepad</title>
      <path
        fill="currentColor"
        d="M2 5h20v14H2zm18 12V7H4v10zM8 9h2v2h2v2h-2v2H8v-2H6v-2h2zm6 0h2v2h-2zm4 4h-2v2h2z"
      />
    </svg>
  );
}

Gamepad.displayName = "Gamepad";
