// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.136Z
// Icon: grid

import type { SVGProps } from "react";

export interface GridProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Grid({ size = 24, ...props }: GridProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>grid</title>
      <path
        fill="currentColor"
        d="M2 2h20v20H2zm2 2v4h4V4zm6 0v4h4V4zm6 0v4h4V4zm4 6h-4v4h4zm0 6h-4v4h4zm-6 4v-4h-4v4zm-6 0v-4H4v4zm-4-6h4v-4H4zm6-4v4h4v-4z"
      />
    </svg>
  );
}

Grid.displayName = "Grid";
