// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.138Z
// Icon: heart

import type { SVGProps } from "react";

export interface HeartProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Heart({ size = 24, ...props }: HeartProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>heart</title>
      <path
        fill="currentColor"
        d="M9 2H5v2H3v2H1v6h2v2h2v2h2v2h2v2h2v2h2v-2h2v-2h2v-2h2v-2h2v-2h2V6h-2V4h-2V2h-4v2h-2v2h-2V4H9zm0 2v2h2v2h2V6h2V4h4v2h2v6h-2v2h-2v2h-2v2h-2v2h-2v-2H9v-2H7v-2H5v-2H3V6h2V4z"
      />
    </svg>
  );
}

Heart.displayName = "Heart";
