// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.140Z
// Icon: home

import type { SVGProps } from "react";

export interface HomeProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Home({ size = 24, ...props }: HomeProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>home</title>
      <path
        fill="currentColor"
        d="M14 2h-4v2H8v2H6v2H4v2H2v2h2v10h7v-6h2v6h7V12h2v-2h-2V8h-2V6h-2V4h-2zm0 2v2h2v2h2v2h2v2h-2v8h-3v-6H9v6H6v-8H4v-2h2V8h2V6h2V4z"
      />
    </svg>
  );
}

Home.displayName = "Home";
