// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.145Z
// Icon: image-broken

import type { SVGProps } from "react";

export interface ImageBrokenProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function ImageBroken({ size = 24, ...props }: ImageBrokenProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>image-broken</title>
      <path
        fill="currentColor"
        d="M22 3H2v18h20v-2h-2v-2h2v-2h-2v-2h2v-2h-2V9h2V7h-2V5h2zm-2 4v2h-2v2h2v2h-2v2h2v2h-2v2H4V5h14v2zm-6 2h-2v2h-2v2H8v2H6v2h2v-2h2v-2h2v-2h2v2h2v-2h-2zM6 7h2v2H6z"
      />
    </svg>
  );
}

ImageBroken.displayName = "ImageBroken";
