// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.141Z
// Icon: image

import type { SVGProps } from "react";

export interface ImageProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Image({ size = 24, ...props }: ImageProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>image</title>
      <path
        fill="currentColor"
        d="M4 3H2v18h20V3zm16 2v14H4V5zm-6 4h-2v2h-2v2H8v2H6v2h2v-2h2v-2h2v-2h2v2h2v2h2v-2h-2v-2h-2zM8 7H6v2h2z"
      />
    </svg>
  );
}

Image.displayName = "Image";
