// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.143Z
// Icon: image-gallery

import type { SVGProps } from "react";

export interface ImageGalleryProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function ImageGallery({ size = 24, ...props }: ImageGalleryProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>image-gallery</title>
      <path
        fill="currentColor"
        d="M2 2h20v16h-5v2h-2v-2H9v2H7v-2H2zm5 18v2H5v-2zm10 0v2h2v-2zm3-16H4v12h16zm-8 4h2v2h-2zm-2 4v-2h2v2zm0 0v2H8v-2zm6 0h-2v-2h2zm0 0h2v2h-2zM8 6H6v2h2z"
      />
    </svg>
  );
}

ImageGallery.displayName = "ImageGallery";
