// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.144Z
// Icon: info-box

import type { SVGProps } from "react";

export interface InfoBoxProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function InfoBox({ size = 24, ...props }: InfoBoxProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>info-box</title>
      <path
        fill="currentColor"
        d="M3 3h2v18H3zm16 0H5v2h14v14H5v2h16V3zm-8 6h2V7h-2zm2 8h-2v-6h2z"
      />
    </svg>
  );
}

InfoBox.displayName = "InfoBox";
