// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.146Z
// Icon: layout-sidebar-left

import type { SVGProps } from "react";

export interface LayoutSidebarLeftProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function LayoutSidebarLeft({
  size = 24,
  ...props
}: LayoutSidebarLeftProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>layout-sidebar-left</title>
      <path fill="currentColor" d="M2 5h20v14H2zm2 2v10h2V7zm4 0v10h12V7z" />
    </svg>
  );
}

LayoutSidebarLeft.displayName = "LayoutSidebarLeft";
