// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.147Z
// Icon: lock

import type { SVGProps } from "react";

export interface LockProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Lock({ size = 24, ...props }: LockProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>lock</title>
      <path
        fill="currentColor"
        d="M15 2H9v2H7v4H4v14h16V8h-3V4h-2zm0 2v4H9V4zm-6 6h9v10H6V10zm4 3h-2v4h2z"
      />
    </svg>
  );
}

Lock.displayName = "Lock";
