// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.148Z
// Icon: menu

import type { SVGProps } from "react";

export interface MenuProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Menu({ size = 24, ...props }: MenuProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>menu</title>
      <path fill="currentColor" d="M4 6h16v2H4zm0 5h16v2H4zm16 5H4v2h16z" />
    </svg>
  );
}

Menu.displayName = "Menu";
