// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.149Z
// Icon: paint-bucket

import type { SVGProps } from "react";

export interface PaintBucketProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function PaintBucket({ size = 24, ...props }: PaintBucketProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>paint-bucket</title>
      <path
        fill="currentColor"
        d="M8 3h8v2H8zm0 2H6v4H4v12h16V9h-2V5h-2v4H8zm8 6h2v8H6v-8h2v6h2v-4h2v2h2v-2h2z"
      />
    </svg>
  );
}

PaintBucket.displayName = "PaintBucket";
