// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.150Z
// Icon: sliders

import type { SVGProps } from "react";

export interface SlidersProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Sliders({ size = 24, ...props }: SlidersProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>sliders</title>
      <path
        fill="currentColor"
        d="M17 4h2v10h-2zm0 12h-2v2h2v2h2v-2h2v-2zm-4-6h-2v10h2zm-8 2H3v2h2v6h2v-6h2v-2zm8-8h-2v2H9v2h6V6h-2zM5 4h2v6H5z"
      />
    </svg>
  );
}

Sliders.displayName = "Sliders";
