// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.152Z
// Icon: sliders-2

import type { SVGProps } from "react";

export interface Sliders_2Props extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Sliders_2({ size = 24, ...props }: Sliders_2Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>sliders-2</title>
      <path
        stroke="currentColor"
        stroke-linecap="square"
        stroke-width="2"
        d="M3 8h4m0 0V6h4v2M7 8v2h4V8m0 0h10M3 16h10m0 0v-2h4v2m-4 0v2h4v-2m0 0h4"
      />
    </svg>
  );
}

Sliders_2.displayName = "Sliders_2";
