// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.155Z
// Icon: upload

import type { SVGProps } from "react";

export interface UploadProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Upload({ size = 24, ...props }: UploadProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>upload</title>
      <path
        fill="currentColor"
        d="M11 5V3h2v2h2v2h2v2h-2V7h-2v10h-2V7H9v2H7V7h2V5zM3 15v6h18v-6h-2v4H5v-4z"
      />
    </svg>
  );
}

Upload.displayName = "Upload";
