// Generated by @pyyupsk/pixelarticons CLI - changes may be overwritten
// Generated at: 2025-10-13T15:41:20.156Z
// Icon: zap

import type { SVGProps } from "react";

export interface ZapProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function Zap({ size = 24, ...props }: ZapProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>zap</title>
      <path
        fill="currentColor"
        d="M12 1h2v8h8v4h-2v-2h-8V5h-2V3h2zM8 7V5h2v2zM6 9V7h2v2zm-2 2V9h2v2zm10 8v2h-2v2h-2v-8H2v-4h2v2h8v6zm2-2v2h-2v-2zm2-2v2h-2v-2zm0 0h2v-2h-2z"
      />
    </svg>
  );
}

Zap.displayName = "Zap";
